image: openjdk:17-alpine

stages:
  - build


build_job:
  stage: build
  before_script:
    - echo "Hello world"
  script:
    - java -version 
  after_script:
    - echo " My build"
  artificats:
    paths:
      - target/devops-0.0.1-SNAPSHOT.jar
    expire_in: 1 days




